### PR TITLE
exporterparser/zipkin: safely retrieve remoteEndpoint serviceName

### LINKED ISSUE #230: exporter/zipkin: missing endpoints in payload cause a panic
Steps to reproduce:

* Download latest collector
* Configure to receive OC agent (--receiver-oc-trace)
* Configure debug-tracer with log level set to debug
* Configure to send to a Zipkin exporter
* Run example/main.go pointed at collector

Expected: Traces are received by Zipkin exporter

Actual: crash seen in OC collector logs

### PR DESCRIPTION
**Pull request by odeke-em**
Safely retrieve the servicename for the remoteEndpoint if no
endpoints were sent in the payload hence a nil Node.

A reduction of PR #229 and originally @pjanotti's endeavor.

Fixes #230

### CODE REVIEW

File: exporter/exporterparser/zipkin.go [hunk 1]
```diff
@@ -132,6 +132,13 @@ func newZipkinExporter(finalEndpointURI, defaultServiceName, defaultLocalEndpoin
 	return zle, nil
 }
 
+func lookupAttribute(node *commonpb.Node, key string) string {
```
Comment (pjanotti) [inline exporter/exporterparser/zipkin.go]: personal preference: nothing against small functions (on the contrary) but I tend to add one that is used just in one place, but I am fine as it is.

File: exporter/exporterparser/zipkin_test.go [hunk 2]
```diff
@@ -112,6 +112,15 @@ exporters:
     {"timestamp": 1472470996403000,"value": "bar"}
   ],
   "tags": {"http.path": "/api","clnt/finagle.version": "6.45.0"}
+},
```
Comment (pjanotti) [inline exporter/exporterparser/zipkin_test.go]: side note: in principle this represents a slightly increase in the probability of the sporadic test failure that we saw in  #181
